version: '3.3'

volumes:
  var-lib-mysql:

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=atelierdb
      - MYSQL_ROOT_PASSWORD=foo
    volumes:
      - var-lib-mysql:/var/lib/mysql

  atelier:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - db
